dynamicgraph::Signal< T, Time > Class Template Reference
dynamicgraph::Signal< T, Time > Class Template Reference
Core classes and objects
Signals link I/O ports of entities. They can be constant-valued signals, or copy the value of a heap variable, or evaluated as a function. See SignalPtr and SignalTimeDependent for other types of signals, and SignalArray for a way of grouping them.
#include <dynamic-graph/signal.h>
Public Types
typedef int * Mutex
typedef int * MutexError
Public Member Functions
Signal (std::string name)
virtual ~Signal ()
virtual void get (std::ostream &value) const
virtual void set (std::istringstream &value)
virtual void trace (std::ostream &os) const
virtual void setConstant (const T &t)
virtual void setReference (const T *t, Mutex *mutexref=NULL)
virtual void setReferenceNonConstant (T *t, Mutex *mutexref=NULL)
virtual void setFunction (boost::function2< T &, T &, Time > t, Mutex *mutexref=NULL)
bool getKeepReference ()
void setKeepReference (const bool &b)
virtual const T & access (const Time &t)
virtual void recompute (const Time &t)
virtual const T & accessCopy () const
virtual std::ostream & display (std::ostream &os) const
virtual const T & operator() (const Time &t)
virtual Signal< T, Time > & operator= (const T &t)
operator const T & () const
virtual void getClassName (std::string &aClassName) const
virtual void checkCompatibility ()
Public Member Functions inherited from dynamicgraph::SignalBase< Time >
SignalBase (std::string name="")
virtual ~SignalBase ()
virtual const Time & getTime () const
virtual void setTime (const Time &t)
const bool & getReady () const
const std::string & getName () const
void getClassName (std::string &aClassName) const
virtual void setPeriodTime (const Time &)
virtual Time getPeriodTime () const
virtual void addDependency (const SignalBase< Time > &)
virtual void removeDependency (const SignalBase< Time > &)
virtual void clearDependencies ()
virtual bool needUpdate (const Time &) const
void setReady (const bool sready=true)
virtual std::ostream & writeGraph (std::ostream &os) const
virtual std::ostream & displayDependencies (std::ostream &os, const int=-1, std::string space="", std::string next1="", std::string="") const
virtual void plug (SignalBase< Time > *sigarg)
virtual void unplug ()
virtual bool isPlugged () const
virtual SignalBase< Time > * getPluged () const
virtual void setConstantDefault ()
std::string shortName () const
virtual void ExtractNodeAndLocalNames (std::string &LocalName, std::string &NodeName) const
Protected Types
enum SignalType {
CONSTANT,
REFERENCE,
REFERENCE_NON_CONST,
FUNCTION
}
Protected Attributes
SignalType signalType
T Tcopy1
T Tcopy2
T * Tcopy
bool copyInit
const T * Treference
T * TreferenceNonConst
boost::function2< T &, T &, Time > Tfunction
bool keepReference
Mutex * providerMutex
Protected Attributes inherited from dynamicgraph::SignalBase< Time >
std::string name
Time signalTime
bool ready
Static Protected Attributes
static const SignalType SIGNAL_TYPE_DEFAULT = CONSTANT
static const bool KEEP_REFERENCE_DEFAULT = false
Detailed Description
template<class T, class Time>
class dynamicgraph::Signal< T, Time >
Signals link I/O ports of entities. They can be constant-valued signals, or copy the value of a heap variable, or evaluated as a function. See SignalPtr and SignalTimeDependent for other types of signals, and SignalArray for a way of grouping them.
There are several ways to specify the value output by a signal:
using the function setConstant(T) to set the value of the signal to T;
using the function setReference(mutex, T*) to set the value from a pointer, whose access is restricted by a mutex;
using the function setFunction(boost::function2) that will be called when the signal's value is accessed.
Member Typedef Documentation
template<class T, class Time> typedef int* dynamicgraph::Signal< T, Time >::Mutex
template<class T, class Time> typedef int* dynamicgraph::Signal< T, Time >::MutexError
Member Enumeration Documentation
template<class T, class Time> enum dynamicgraph::Signal::SignalType protected
Enumerator
CONSTANT
REFERENCE
REFERENCE_NON_CONST
FUNCTION
Constructor & Destructor Documentation
template<class T , class Time > dynamicgraph::Signal< T, Time >::Signal (std::string name)
References dynamicgraph::Signal< T, Time >::set().
template<class T, class Time> virtual dynamicgraph::Signal< T, Time >::~Signal () inline virtual
Member Function Documentation
template<class T , class Time> const T & dynamicgraph::Signal< T, Time >::access (const Time & t) virtual
Reimplemented in dynamicgraph::SignalPtr< T, Time >, dynamicgraph::SignalTimeDependent< T, Time >, and dynamicgraph::SignalTimeDependent< int, int >.
References dynamicgraph::Signal< T, Time >::accessCopy(), dynamicgraph::Signal< T, Time >::CONSTANT, dynamicgraph::Signal< T, Time >::copyInit, dynamicgraph::Signal< T, Time >::FUNCTION, dynamicgraph::SignalBase< Time >::getReady(), dynamicgraph::Signal< T, Time >::providerMutex, dynamicgraph::Signal< T, Time >::REFERENCE, dynamicgraph::Signal< T, Time >::REFERENCE_NON_CONST, dynamicgraph::SignalBase< Time >::setReady(), dynamicgraph::SignalBase< Time >::setTime(), dynamicgraph::SignalBase< Time >::signalTime, dynamicgraph::Signal< T, Time >::signalType, dynamicgraph::Signal< T, Time >::Tfunction, and dynamicgraph::Signal< T, Time >::Treference.
Referenced by dynamicgraph::SignalTimeDependent< T, Time >::access(), dynamicgraph::SignalPtr< T, Time >::access(), dynamicgraph::Signal< T, Time >::accessCopy(), dynamicgraph::Signal< int, int >::operator()(), dynamicgraph::Signal< int, int >::recompute(), and dynamicgraph::Signal< int, int >::setKeepReference().
template<class T , class Time > const T & dynamicgraph::Signal< T, Time >::accessCopy () const virtual
Reimplemented in dynamicgraph::SignalPtr< T, Time >.
References dynamicgraph::Signal< T, Time >::access(), and dynamicgraph::Signal< T, Time >::Tcopy.
Referenced by dynamicgraph::SignalTimeDependent< T, Time >::access(), dynamicgraph::SignalPtr< T, Time >::access(), dynamicgraph::Signal< T, Time >::access(), dynamicgraph::SignalPtr< T, Time >::accessCopy(), dynamicgraph::Signal< T, Time >::get(), dynamicgraph::Signal< T, Time >::operator const T &(), dynamicgraph::Signal< int, int >::recompute(), dynamicgraph::Signal< T, Time >::setFunction(), and dynamicgraph::Signal< T, Time >::trace().
template<class T, class Time> virtual void dynamicgraph::Signal< T, Time >::checkCompatibility () inline virtual
Reimplemented from dynamicgraph::SignalBase< Time >.
Reimplemented in dynamicgraph::SignalPtr< T, Time >.
Referenced by dynamicgraph::SignalPtr< T, Time >::checkCompatibility().
template<class T , class Time > std::ostream & dynamicgraph::Signal< T, Time >::display (std::ostream & os) const virtual
Reimplemented from dynamicgraph::SignalBase< Time >.
Reimplemented in dynamicgraph::SignalPtr< T, Time >.
References dynamicgraph::SignalBase< Time >::name, and dynamicgraph::Signal< T, Time >::signalType.
Referenced by dynamicgraph::SignalPtr< T, Time >::display(), dynamicgraph::Signal< T, Time >::operator=(), and dynamicgraph::Signal< int, int >::recompute().
template<class T , class Time > void dynamicgraph::Signal< T, Time >::get (std::ostream & value) const virtual
Reimplemented from dynamicgraph::SignalBase< Time >.
References dynamicgraph::Signal< T, Time >::accessCopy(), and dynamicgraph::Signal< T, Time >::trace().
Referenced by dynamicgraph::Signal< T, Time >::set().
template<class T, class Time> virtual void dynamicgraph::Signal< T, Time >::getClassName (std::string & aClassName) const inline virtual
template<class T, class Time> bool dynamicgraph::Signal< T, Time >::getKeepReference () inline
template<class T, class Time> dynamicgraph::Signal< T, Time >::operator const T & () const inline
References dynamicgraph::Signal< T, Time >::accessCopy().
template<class T, class Time> virtual const T& dynamicgraph::Signal< T, Time >::operator() (const Time & t) inline virtual
Reimplemented in dynamicgraph::SignalPtr< T, Time >, dynamicgraph::SignalTimeDependent< T, Time >, and dynamicgraph::SignalTimeDependent< int, int >.
template<class T, class Time > Signal< T, Time > & dynamicgraph::Signal< T, Time >::operator= (const T & t) virtual
Reimplemented in dynamicgraph::SignalPtr< T, Time >.
References dynamicgraph::Signal< T, Time >::display(), dynamicgraph::Signal< T, Time >::keepReference, dynamicgraph::Signal< T, Time >::providerMutex, dynamicgraph::Signal< T, Time >::REFERENCE_NON_CONST, dynamicgraph::Signal< T, Time >::setConstant(), dynamicgraph::Signal< T, Time >::signalType, and dynamicgraph::Signal< T, Time >::TreferenceNonConst.
Referenced by dynamicgraph::Signal< int, int >::operator()().
template<class T, class Time> virtual void dynamicgraph::Signal< T, Time >::recompute (const Time & t) inline virtual
Reimplemented from dynamicgraph::SignalBase< Time >.
template<class T , class Time > void dynamicgraph::Signal< T, Time >::set (std::istringstream & value) virtual
Reimplemented from dynamicgraph::SignalBase< Time >.
References dynamicgraph::Signal< T, Time >::get(), and dynamicgraph::signal_cast().
Referenced by dynamicgraph::Signal< T, Time >::Signal().
template<class T, class Time > void dynamicgraph::Signal< T, Time >::setConstant (const T & t) virtual
Reimplemented in dynamicgraph::SignalPtr< T, Time >.
References dynamicgraph::Signal< T, Time >::CONSTANT, dynamicgraph::SignalBase< Time >::setReady(), dynamicgraph::Signal< T, Time >::setReference(), and dynamicgraph::Signal< T, Time >::signalType.
Referenced by dynamicgraph::Signal< T, Time >::operator=(), dynamicgraph::SignalPtr< T, Time >::setConstant(), dynamicgraph::SignalPtr< T, Time >::setConstantDefault(), dynamicgraph::Signal< T, Time >::trace(), and dynamicgraph::Signal< int, int >::~Signal().
template<class T, class Time> void dynamicgraph::Signal< T, Time >::setFunction (boost::function2< T &, T &, Time > t, Mutex * mutexref = NULL) virtual
References dynamicgraph::Signal< T, Time >::accessCopy(), dynamicgraph::Signal< T, Time >::copyInit, dynamicgraph::Signal< T, Time >::FUNCTION, dynamicgraph::Signal< T, Time >::providerMutex, dynamicgraph::SignalBase< Time >::setReady(), dynamicgraph::Signal< T, Time >::signalType, and dynamicgraph::Signal< T, Time >::Tfunction.
Referenced by dynamicgraph::SignalPtr< T, Time >::setFunction(), dynamicgraph::Signal< T, Time >::setReferenceNonConstant(), dynamicgraph::SignalTimeDependent< T, Time >::SignalTimeDependent(), and dynamicgraph::Signal< int, int >::~Signal().
template<class T, class Time> void dynamicgraph::Signal< T, Time >::setKeepReference (const bool & b) inline
template<class T, class Time > void dynamicgraph::Signal< T, Time >::setReference (const T * t, Mutex * mutexref = NULL) virtual
References dynamicgraph::Signal< T, Time >::copyInit, dynamicgraph::Signal< T, Time >::providerMutex, dynamicgraph::Signal< T, Time >::REFERENCE, dynamicgraph::SignalBase< Time >::setReady(), dynamicgraph::Signal< T, Time >::setReferenceNonConstant(), dynamicgraph::Signal< T, Time >::signalType, and dynamicgraph::Signal< T, Time >::Treference.
Referenced by dynamicgraph::SignalPtr< T, Time >::plug(), dynamicgraph::Signal< T, Time >::setConstant(), dynamicgraph::SignalPtr< T, Time >::setReference(), and dynamicgraph::Signal< int, int >::~Signal().
template<class T, class Time > void dynamicgraph::Signal< T, Time >::setReferenceNonConstant (T * t, Mutex * mutexref = NULL) virtual
References dynamicgraph::Signal< T, Time >::copyInit, dynamicgraph::Signal< T, Time >::providerMutex, dynamicgraph::Signal< T, Time >::REFERENCE_NON_CONST, dynamicgraph::Signal< T, Time >::setFunction(), dynamicgraph::SignalBase< Time >::setReady(), dynamicgraph::Signal< T, Time >::signalType, dynamicgraph::Signal< T, Time >::Treference, and dynamicgraph::Signal< T, Time >::TreferenceNonConst.
Referenced by dynamicgraph::Signal< T, Time >::setReference(), and dynamicgraph::Signal< int, int >::~Signal().
template<class T , class Time > void dynamicgraph::Signal< T, Time >::trace (std::ostream & os) const virtual
Reimplemented from dynamicgraph::SignalBase< Time >.
References dynamicgraph::Signal< T, Time >::accessCopy(), dynamicgraph::Signal< T, Time >::copyInit, DG_RETHROW, DG_THROW, dynamicgraph::ExceptionSignal::SET_IMPOSSIBLE, dynamicgraph::Signal< T, Time >::setConstant(), dynamicgraph::Signal< T, Time >::Tcopy, dynamicgraph::Signal< T, Time >::Tcopy1, and dynamicgraph::Signal< T, Time >::Tcopy2.
Referenced by dynamicgraph::Signal< T, Time >::get(), and dynamicgraph::Signal< int, int >::~Signal().
Member Data Documentation
template<class T, class Time> bool dynamicgraph::Signal< T, Time >::copyInit protected
Referenced by dynamicgraph::Signal< T, Time >::access(), dynamicgraph::Signal< T, Time >::setFunction(), dynamicgraph::Signal< T, Time >::setReference(), dynamicgraph::Signal< T, Time >::setReferenceNonConstant(), and dynamicgraph::Signal< T, Time >::trace().
template<class T, class Time> const bool dynamicgraph::Signal< T, Time >::KEEP_REFERENCE_DEFAULT = false static protected
template<class T, class Time> bool dynamicgraph::Signal< T, Time >::keepReference protected
Referenced by dynamicgraph::Signal< int, int >::getKeepReference(), and dynamicgraph::Signal< T, Time >::operator=().
template<class T, class Time> Mutex* dynamicgraph::Signal< T, Time >::providerMutex protected
Referenced by dynamicgraph::Signal< T, Time >::access(), dynamicgraph::Signal< T, Time >::operator=(), dynamicgraph::Signal< T, Time >::setFunction(), dynamicgraph::Signal< T, Time >::setReference(), and dynamicgraph::Signal< T, Time >::setReferenceNonConstant().
template<class T, class Time> const SignalType dynamicgraph::Signal< T, Time >::SIGNAL_TYPE_DEFAULT = CONSTANT static protected
template<class T, class Time> SignalType dynamicgraph::Signal< T, Time >::signalType protected
Referenced by dynamicgraph::Signal< T, Time >::access(), dynamicgraph::Signal< T, Time >::display(), dynamicgraph::Signal< T, Time >::operator=(), dynamicgraph::Signal< T, Time >::setConstant(), dynamicgraph::Signal< T, Time >::setFunction(), dynamicgraph::Signal< T, Time >::setReference(), and dynamicgraph::Signal< T, Time >::setReferenceNonConstant().
template<class T, class Time> T* dynamicgraph::Signal< T, Time >::Tcopy protected
Referenced by dynamicgraph::Signal< T, Time >::accessCopy(), dynamicgraph::Signal< int, int >::checkCompatibility(), and dynamicgraph::Signal< T, Time >::trace().
template<class T, class Time> T dynamicgraph::Signal< T, Time >::Tcopy1 protected
Referenced by dynamicgraph::Signal< T, Time >::trace().
template<class T, class Time> T dynamicgraph::Signal< T, Time >::Tcopy2 protected
Referenced by dynamicgraph::Signal< T, Time >::trace().
template<class T, class Time> boost::function2<T&,T&,Time> dynamicgraph::Signal< T, Time >::Tfunction protected
Referenced by dynamicgraph::Signal< T, Time >::access(), and dynamicgraph::Signal< T, Time >::setFunction().
template<class T, class Time> const T* dynamicgraph::Signal< T, Time >::Treference protected
Referenced by dynamicgraph::Signal< T, Time >::access(), dynamicgraph::Signal< T, Time >::setReference(), and dynamicgraph::Signal< T, Time >::setReferenceNonConstant().
template<class T, class Time> T* dynamicgraph::Signal< T, Time >::TreferenceNonConst protected
Referenced by dynamicgraph::Signal< T, Time >::operator=(), and dynamicgraph::Signal< T, Time >::setReferenceNonConstant().