dynamicgraph::DefaultCastRegisterer< T > Class Template Reference
dynamicgraph::DefaultCastRegisterer< T > Class Template Reference
This class can be used to register default casts, i.e.
#include <dynamic-graph/signal-cast-helper.h>
Public Member Functions
DefaultCastRegisterer ()
Public Member Functions inherited from dynamicgraph::SignalCastRegisterer
SignalCastRegisterer (const std::type_info &type, SignalCaster::displayer_type displayer, SignalCaster::caster_type caster, SignalCaster::tracer_type tracer)
Static Public Member Functions
static boost::any cast (std::istringstream &iss)
A default version of the caster, to serialize directly from std::in.
static void disp (const boost::any &object, std::ostream &os)
static void trace (const boost::any &object, std::ostream &os)
Detailed Description
template<typename T>
class dynamicgraph::DefaultCastRegisterer< T >
This class can be used to register default casts, i.e.
casts already supported by the object to an std::iostream through the operators >> and << .
Constructor & Destructor Documentation
template<typename T > dynamicgraph::DefaultCastRegisterer< T >::DefaultCastRegisterer () inline
References dynamicgraph::DefaultCastRegisterer< T >::cast().
Member Function Documentation
template<typename T > boost::any dynamicgraph::DefaultCastRegisterer< T >::cast (std::istringstream & iss) static
A default version of the caster, to serialize directly from std::in.
References dynamicgraph::ExceptionSignal::GENERIC.
Referenced by dynamicgraph::SignalCast< T >::cast_(), and dynamicgraph::DefaultCastRegisterer< T >::DefaultCastRegisterer().
template<typename T > static void dynamicgraph::DefaultCastRegisterer< T >::disp (const boost::any & object, std::ostream & os) inline static
Referenced by dynamicgraph::SignalCast< T >::disp_(), dynamicgraph::DefaultCastRegisterer< T >::trace(), and dynamicgraph::SignalCast< T >::trace().
template<typename T > static void dynamicgraph::DefaultCastRegisterer< T >::trace (const boost::any & object, std::ostream & os) inline static
References dynamicgraph::DefaultCastRegisterer< T >::disp().
Referenced by dynamicgraph::SignalCast< T >::trace_().