dynamicgraph::SignalBase< Time > Class Template Reference
dynamicgraph::SignalBase< Time > Class Template Reference
The base class for signals: not to be used as such.
#include <dynamic-graph/signal-base.h>
Public Member Functions
SignalBase (std::string name="")
virtual ~SignalBase ()
Time
virtual const Time & getTime () const
virtual void setTime (const Time &t)
const bool & getReady () const
const std::string & getName () const
void getClassName (std::string &aClassName) const
virtual void setPeriodTime (const Time &)
virtual Time getPeriodTime () const
Dependencies
virtual void addDependency (const SignalBase< Time > &)
virtual void removeDependency (const SignalBase< Time > &)
virtual void clearDependencies ()
virtual bool needUpdate (const Time &) const
void setReady (const bool sready=true)
virtual std::ostream & writeGraph (std::ostream &os) const
virtual std::ostream & displayDependencies (std::ostream &os, const int=-1, std::string space="", std::string next1="", std::string="") const
Plug
virtual void plug (SignalBase< Time > *sigarg)
virtual void unplug ()
virtual bool isPlugged () const
virtual SignalBase< Time > * getPluged () const
virtual void setConstantDefault ()
Set
virtual void set (std::istringstream &)
virtual void get (std::ostream &) const
virtual void recompute (const Time &)
virtual void trace (std::ostream &) const
Display
virtual std::ostream & display (std::ostream &os) const
std::string shortName () const
Information providers
virtual void ExtractNodeAndLocalNames (std::string &LocalName, std::string &NodeName) const
Test
virtual void checkCompatibility ()
Protected Attributes
std::string name
Time signalTime
bool ready
Detailed Description
template<class Time>
class dynamicgraph::SignalBase< Time >
The base class for signals: not to be used as such.
Signal values can be accessed programmatically using the access () or accessCopy () methods; the former directly accesses the value of the signal, which can involve an extra computation, while the latter accesses a cached value, or 'copy'.
Constructor & Destructor Documentation
template<class Time> dynamicgraph::SignalBase< Time >::SignalBase (std::string name = "") inline explicit
template<class Time> virtual dynamicgraph::SignalBase< Time >::~SignalBase () inline virtual
Member Function Documentation
template<class Time> virtual void dynamicgraph::SignalBase< Time >::addDependency (const SignalBase< Time > &) inline virtual
Reimplemented in dynamicgraph::SignalTimeDependent< T, Time >, and dynamicgraph::SignalTimeDependent< int, int >.
template<class Time> virtual void dynamicgraph::SignalBase< Time >::checkCompatibility () inline virtual
Reimplemented in dynamicgraph::Signal< T, Time >, dynamicgraph::Signal< int, int >, and dynamicgraph::SignalPtr< T, Time >.
Referenced by dynamicgraph::SignalPtr< T, Time >::plug().
template<class Time> virtual void dynamicgraph::SignalBase< Time >::clearDependencies () inline virtual
Reimplemented in dynamicgraph::SignalPtr< T, Time >, dynamicgraph::SignalTimeDependent< T, Time >, and dynamicgraph::SignalTimeDependent< int, int >.
template<class Time> virtual std::ostream& dynamicgraph::SignalBase< Time >::display (std::ostream & os) const inline virtual
Reimplemented in dynamicgraph::Signal< T, Time >, dynamicgraph::Signal< int, int >, and dynamicgraph::SignalPtr< T, Time >.
Referenced by dynamicgraph::SignalBase< int >::displayDependencies().
template<class Time> virtual std::ostream& dynamicgraph::SignalBase< Time >::displayDependencies (std::ostream & os, const int = -1, std::string space = "", std::string next1 = "", std::string = "") const inline virtual
Reimplemented in dynamicgraph::SignalPtr< T, Time >, dynamicgraph::SignalTimeDependent< T, Time >, and dynamicgraph::SignalTimeDependent< int, int >.
Referenced by dynamicgraph::SignalPtr< T, Time >::displayDependencies().
template<class Time> virtual void dynamicgraph::SignalBase< Time >::ExtractNodeAndLocalNames (std::string & LocalName, std::string & NodeName) const inline virtual
Referenced by dynamicgraph::SignalPtr< T, Time >::writeGraph().
template<class Time> virtual void dynamicgraph::SignalBase< Time >::get (std::ostream &) const inline virtual
Reimplemented in dynamicgraph::Signal< T, Time >, and dynamicgraph::Signal< int, int >.
template<class Time> void dynamicgraph::SignalBase< Time >::getClassName (std::string & aClassName) const inline
template<class Time> const std::string& dynamicgraph::SignalBase< Time >::getName () const inline
Referenced by dynamicgraph::SignalBase< int >::checkCompatibility(), dynamicgraph::SignalBase< int >::ExtractNodeAndLocalNames(), dynamicgraph::SignalBase< int >::get(), dynamicgraph::SignalPtr< T, Time >::plug(), dynamicgraph::SignalBase< int >::plug(), dynamicgraph::SignalBase< int >::recompute(), dynamicgraph::SignalBase< int >::set(), dynamicgraph::SignalBase< int >::setConstantDefault(), dynamicgraph::SignalBase< int >::trace(), and dynamicgraph::SignalBase< int >::unplug().
template<class Time> virtual Time dynamicgraph::SignalBase< Time >::getPeriodTime () const inline virtual
Reimplemented in dynamicgraph::SignalTimeDependent< T, Time >, and dynamicgraph::SignalTimeDependent< int, int >.
template<class Time> virtual SignalBase<Time>* dynamicgraph::SignalBase< Time >::getPluged () const inline virtual
Reimplemented in dynamicgraph::SignalPtr< T, Time >.
template<class Time> const bool& dynamicgraph::SignalBase< Time >::getReady () const inline
Referenced by dynamicgraph::Signal< T, Time >::access().
template<class Time> virtual const Time& dynamicgraph::SignalBase< Time >::getTime () const inline virtual
Reimplemented in dynamicgraph::SignalPtr< T, Time >.
Referenced by dynamicgraph::SignalPtr< T, Time >::getTime(), and dynamicgraph::TimeDependency< Time >::needUpdate().
template<class Time> virtual bool dynamicgraph::SignalBase< Time >::isPlugged () const inline virtual
Reimplemented in dynamicgraph::SignalPtr< T, Time >.
template<class Time> virtual bool dynamicgraph::SignalBase< Time >::needUpdate (const Time &) const inline virtual
Reimplemented in dynamicgraph::SignalPtr< T, Time >, dynamicgraph::SignalTimeDependent< T, Time >, and dynamicgraph::SignalTimeDependent< int, int >.
Referenced by dynamicgraph::TimeDependency< Time >::needUpdate(), and dynamicgraph::SignalPtr< T, Time >::needUpdate().
template<class Time> virtual void dynamicgraph::SignalBase< Time >::plug (SignalBase< Time > * sigarg) inline virtual
Reimplemented in dynamicgraph::SignalPtr< T, Time >.
template<class Time> virtual void dynamicgraph::SignalBase< Time >::recompute (const Time &) inline virtual
Reimplemented in dynamicgraph::Signal< T, Time >, and dynamicgraph::Signal< int, int >.
template<class Time> virtual void dynamicgraph::SignalBase< Time >::removeDependency (const SignalBase< Time > &) inline virtual
Reimplemented in dynamicgraph::SignalTimeDependent< T, Time >, and dynamicgraph::SignalTimeDependent< int, int >.
template<class Time> virtual void dynamicgraph::SignalBase< Time >::set (std::istringstream &) inline virtual
Reimplemented in dynamicgraph::Signal< T, Time >, and dynamicgraph::Signal< int, int >.
template<class Time> virtual void dynamicgraph::SignalBase< Time >::setConstantDefault () inline virtual
Reimplemented in dynamicgraph::SignalPtr< T, Time >.
template<class Time> virtual void dynamicgraph::SignalBase< Time >::setPeriodTime (const Time &) inline virtual
Reimplemented in dynamicgraph::SignalTimeDependent< T, Time >, and dynamicgraph::SignalTimeDependent< int, int >.
template<class Time> void dynamicgraph::SignalBase< Time >::setReady (const bool sready = true) inline
Referenced by dynamicgraph::SignalTimeDependent< T, Time >::access(), dynamicgraph::Signal< T, Time >::access(), dynamicgraph::Signal< T, Time >::setConstant(), dynamicgraph::Signal< T, Time >::setFunction(), dynamicgraph::Signal< T, Time >::setReference(), and dynamicgraph::Signal< T, Time >::setReferenceNonConstant().
template<class Time> virtual void dynamicgraph::SignalBase< Time >::setTime (const Time & t) inline virtual
Referenced by dynamicgraph::Signal< T, Time >::access().
template<class Time> std::string dynamicgraph::SignalBase< Time >::shortName () const inline
template<class Time> virtual void dynamicgraph::SignalBase< Time >::trace (std::ostream &) const inline virtual
Reimplemented in dynamicgraph::Signal< T, Time >, and dynamicgraph::Signal< int, int >.
template<class Time> virtual void dynamicgraph::SignalBase< Time >::unplug () inline virtual
Reimplemented in dynamicgraph::SignalPtr< T, Time >.
template<class Time> virtual std::ostream& dynamicgraph::SignalBase< Time >::writeGraph (std::ostream & os) const inline virtual
Reimplemented in dynamicgraph::SignalPtr< T, Time >, dynamicgraph::SignalTimeDependent< T, Time >, and dynamicgraph::SignalTimeDependent< int, int >.
Member Data Documentation
template<class Time> std::string dynamicgraph::SignalBase< Time >::name protected
Referenced by dynamicgraph::Signal< T, Time >::display(), dynamicgraph::SignalBase< int >::display(), dynamicgraph::SignalBase< int >::getClassName(), dynamicgraph::Signal< int, int >::getClassName(), dynamicgraph::SignalBase< int >::getName(), and dynamicgraph::SignalBase< int >::shortName().
template<class Time> bool dynamicgraph::SignalBase< Time >::ready protected
Referenced by dynamicgraph::SignalBase< int >::getReady(), dynamicgraph::SignalBase< int >::needUpdate(), and dynamicgraph::SignalBase< int >::setReady().
template<class Time> Time dynamicgraph::SignalBase< Time >::signalTime protected
Referenced by dynamicgraph::Signal< T, Time >::access(), dynamicgraph::SignalBase< int >::getTime(), and dynamicgraph::SignalBase< int >::setTime().