dynamic-graph: dynamicgraph::SignalPtr< T, Time > Class Template Reference
dynamicgraph::SignalPtr< T, Time > Class Template Reference
[Core classes and objects]
This is the only type of signal that can be plugged to, using the plug () command.
#include <dynamic-graph/signal-ptr.h>
Public Member Functions
SignalPtr (Signal< T, Time > *ptr, std::string name="")
virtual ~SignalPtr ()
Signal< T, Time > * getPtr ()
const Signal< T, Time > * getPtr () const
SignalBase< Time > * getAbstractPtr ()
const SignalBase< Time > * getAbstractPtr () const
virtual void plug (SignalBase< Time > *ref)
virtual void unplug ()
virtual bool isPluged () const
virtual SignalBase< Time > * getPluged () const
virtual bool isAbstractPluged () const
virtual const Time & getTime () const
Signal< T, Time > * operator-> ()
const Signal< T, Time > * operator-> () const
Signal< T, Time > & operator* ()
const Signal< T, Time > & operator* () const
operator bool () const
virtual bool needUpdate (const Time &t) const
virtual std::ostream & writeGraph (std::ostream &os) const
virtual std::ostream & display (std::ostream &os) const
virtual const T & operator() (const Time &t)
virtual const T & access (const Time &t)
virtual const T & accessCopy () const
void setConstantDefault (const T &t)
virtual void setConstantDefault ()
void unsetConstantDefault ()
virtual void setConstant (const T &t)
virtual void setReference (const T *t, typename Signal< T, Time >::Mutex *m=NULL)
virtual void setFunction (boost::function2< T &, T &, Time > t, typename Signal< T, Time >::Mutex *m=NULL)
virtual Signal< T, Time > & operator= (const T &t)
virtual std::ostream & displayDependencies (std::ostream &os, const int depth=-1, std::string space="", std::string next1="", std::string next2="") const
Protected Member Functions
bool autoref () const
virtual void addDependency ()
virtual void removeDependency ()
virtual void clearDependencies ()
Protected Attributes
Signal< T, Time > * signalPtr
bool modeNoThrow
bool transmitAbstract
SignalBase< Time > * abstractTransmitter
T * transmitAbstractData
Detailed Description
template<class T, class Time>
class dynamicgraph::SignalPtr< T, Time >
This is the only type of signal that can be plugged to, using the plug () command.
In that sense, when plugged into, it acts as a "pointer" to the input signal, hence the name. Operator -> is also overloaded and can be used to access the pointed signal.
Constructor & Destructor Documentation
template<class T , class Time > dynamicgraph::SignalPtr< T, Time >::SignalPtr (Signal< T, Time > * ptr, std::string name = "") [inline]
template<class T , class Time > virtual dynamicgraph::SignalPtr< T, Time >::~SignalPtr () [inline, virtual]
References dynamicgraph::SignalPtr< T, Time >::signalPtr.
Member Function Documentation
template<class T , class Time > const T & dynamicgraph::SignalPtr< T, Time >::access (const Time & t) [inline, virtual]
Reimplemented from dynamicgraph::Signal< T, Time >.
References dynamicgraph::SignalPtr< T, Time >::abstractTransmitter, dynamicgraph::SignalPtr< T, Time >::accessCopy(), dynamicgraph::SignalPtr< T, Time >::autoref(), dgTDEBUGIN, dgTDEBUGOUT, dynamicgraph::SignalPtr< T, Time >::getPtr(), dynamicgraph::SignalPtr< T, Time >::isPluged(), dynamicgraph::SignalPtr< T, Time >::modeNoThrow, dynamicgraph::SignalPtr< T, Time >::transmitAbstract, and dynamicgraph::SignalPtr< T, Time >::transmitAbstractData.
Referenced by dynamicgraph::SignalPtr< T, Time >::operator()().
template<class T , class Time > const T & dynamicgraph::SignalPtr< T, Time >::accessCopy () const [inline, virtual]
Reimplemented from dynamicgraph::Signal< T, Time >.
References dynamicgraph::SignalPtr< T, Time >::autoref(), dynamicgraph::SignalPtr< T, Time >::getPtr(), dynamicgraph::SignalPtr< T, Time >::isPluged(), dynamicgraph::SignalPtr< T, Time >::modeNoThrow, dynamicgraph::SignalPtr< T, Time >::transmitAbstract, and dynamicgraph::SignalPtr< T, Time >::transmitAbstractData.
Referenced by dynamicgraph::SignalPtr< T, Time >::access(), and dynamicgraph::SignalPtr< T, Time >::setConstantDefault().
template<class T , class Time > virtual void dynamicgraph::SignalPtr< T, Time >::addDependency () [inline, protected, virtual]
template<class T , class Time > bool dynamicgraph::SignalPtr< T, Time >::autoref () const [inline, protected]
References dynamicgraph::SignalPtr< T, Time >::signalPtr.
Referenced by dynamicgraph::SignalPtr< T, Time >::access(), dynamicgraph::SignalPtr< T, Time >::accessCopy(), dynamicgraph::SignalPtr< T, Time >::display(), dynamicgraph::SignalPtr< T, Time >::displayDependencies(), dynamicgraph::SignalPtr< T, Time >::getTime(), dynamicgraph::SignalPtr< T, Time >::needUpdate(), and dynamicgraph::SignalPtr< T, Time >::writeGraph().
template<class T , class Time > virtual void dynamicgraph::SignalPtr< T, Time >::clearDependencies () [inline, protected, virtual]
Reimplemented from dynamicgraph::SignalBase< Time >.
template<class T , class Time > std::ostream & dynamicgraph::SignalPtr< T, Time >::display (std::ostream & os) const [inline, virtual]
Reimplemented from dynamicgraph::Signal< T, Time >.
References dynamicgraph::SignalPtr< T, Time >::autoref(), dgTDEBUGIN, dgTDEBUGOUT, dynamicgraph::SignalPtr< T, Time >::isAbstractPluged(), dynamicgraph::SignalPtr< T, Time >::isPluged(), and dynamicgraph::SignalPtr< T, Time >::signalPtr.
template<class T , class Time > std::ostream & dynamicgraph::SignalPtr< T, Time >::displayDependencies (std::ostream & os, const int depth = -1, std::string space = "", std::string next1 = "", std::string next2 = "") const [inline, virtual]
Reimplemented from dynamicgraph::SignalBase< Time >.
References dynamicgraph::SignalPtr< T, Time >::autoref(), dgTDEBUGIN, dgTDEBUGOUT, dynamicgraph::SignalPtr< T, Time >::getAbstractPtr(), and dynamicgraph::SignalPtr< T, Time >::isAbstractPluged().
template<class T , class Time > const SignalBase< Time > * dynamicgraph::SignalPtr< T, Time >::getAbstractPtr () const [inline]
References dynamicgraph::SignalPtr< T, Time >::abstractTransmitter, DG_THROW, dynamicgraph::SignalBase< Time >::getName(), dynamicgraph::SignalPtr< T, Time >::isAbstractPluged(), dynamicgraph::ExceptionSignal::NOT_INITIALIZED, and dynamicgraph::SignalPtr< T, Time >::signalPtr.
template<class T , class Time > SignalBase< Time > * dynamicgraph::SignalPtr< T, Time >::getAbstractPtr () [inline]
References dynamicgraph::SignalPtr< T, Time >::abstractTransmitter, DG_THROW, dynamicgraph::SignalBase< Time >::getName(), dynamicgraph::SignalPtr< T, Time >::isAbstractPluged(), dynamicgraph::ExceptionSignal::NOT_INITIALIZED, and dynamicgraph::SignalPtr< T, Time >::signalPtr.
Referenced by dynamicgraph::SignalPtr< T, Time >::displayDependencies(), dynamicgraph::SignalPtr< T, Time >::getTime(), dynamicgraph::SignalPtr< T, Time >::needUpdate(), and dynamicgraph::SignalPtr< T, Time >::writeGraph().
template<class T , class Time > virtual SignalBase<Time>* dynamicgraph::SignalPtr< T, Time >::getPluged () const [inline, virtual]
Reimplemented from dynamicgraph::SignalBase< Time >.
References dynamicgraph::SignalPtr< T, Time >::signalPtr.
template<class T , class Time > const Signal< T, Time > * dynamicgraph::SignalPtr< T, Time >::getPtr () const [inline]
References DG_THROW, dgTDEBUGIN, dgTDEBUGOUT, dynamicgraph::SignalBase< Time >::getName(), dynamicgraph::SignalPtr< T, Time >::isPluged(), dynamicgraph::ExceptionSignal::NOT_INITIALIZED, and dynamicgraph::SignalPtr< T, Time >::signalPtr.
template<class T , class Time > Signal< T, Time > * dynamicgraph::SignalPtr< T, Time >::getPtr () [inline]
References DG_THROW, dgTDEBUGIN, dgTDEBUGOUT, dynamicgraph::SignalBase< Time >::getName(), dynamicgraph::SignalPtr< T, Time >::isPluged(), dynamicgraph::ExceptionSignal::NOT_INITIALIZED, and dynamicgraph::SignalPtr< T, Time >::signalPtr.
Referenced by dynamicgraph::SignalPtr< T, Time >::access(), dynamicgraph::SignalPtr< T, Time >::accessCopy(), dynamicgraph::SignalPtr< T, Time >::operator*(), and dynamicgraph::SignalPtr< T, Time >::operator->().
template<class T , class Time > const Time & dynamicgraph::SignalPtr< T, Time >::getTime () const [inline, virtual]
Reimplemented from dynamicgraph::SignalBase< Time >.
References dynamicgraph::SignalPtr< T, Time >::autoref(), dynamicgraph::SignalPtr< T, Time >::getAbstractPtr(), and dynamicgraph::SignalPtr< T, Time >::isAbstractPluged().
template<class T , class Time > bool dynamicgraph::SignalPtr< T, Time >::isAbstractPluged () const [inline, virtual]
References dynamicgraph::SignalPtr< T, Time >::abstractTransmitter, and dynamicgraph::SignalPtr< T, Time >::signalPtr.
Referenced by dynamicgraph::SignalPtr< T, Time >::display(), dynamicgraph::SignalPtr< T, Time >::displayDependencies(), dynamicgraph::SignalPtr< T, Time >::getAbstractPtr(), dynamicgraph::SignalPtr< T, Time >::getTime(), dynamicgraph::SignalPtr< T, Time >::needUpdate(), and dynamicgraph::SignalPtr< T, Time >::writeGraph().
template<class T , class Time > virtual bool dynamicgraph::SignalPtr< T, Time >::isPluged () const [inline, virtual]
Reimplemented from dynamicgraph::SignalBase< Time >.
References dynamicgraph::SignalPtr< T, Time >::signalPtr.
Referenced by dynamicgraph::SignalPtr< T, Time >::access(), dynamicgraph::SignalPtr< T, Time >::accessCopy(), dynamicgraph::SignalPtr< T, Time >::display(), dynamicgraph::SignalPtr< T, Time >::getPtr(), and dynamicgraph::SignalPtr< T, Time >::operator bool().
template<class T , class Time > bool dynamicgraph::SignalPtr< T, Time >::needUpdate (const Time & t) const [inline, virtual]
Reimplemented from dynamicgraph::SignalBase< Time >.
References dynamicgraph::SignalPtr< T, Time >::autoref(), dynamicgraph::SignalPtr< T, Time >::getAbstractPtr(), and dynamicgraph::SignalPtr< T, Time >::isAbstractPluged().
template<class T , class Time > dynamicgraph::SignalPtr< T, Time >::operator bool () const [inline]
References dynamicgraph::SignalPtr< T, Time >::isPluged().
template<class T , class Time > const T & dynamicgraph::SignalPtr< T, Time >::operator() (const Time & t) [inline, virtual]
Reimplemented from dynamicgraph::Signal< T, Time >.
References dynamicgraph::SignalPtr< T, Time >::access().
template<class T , class Time > const Signal<T,Time>& dynamicgraph::SignalPtr< T, Time >::operator* () const [inline]
References dynamicgraph::SignalPtr< T, Time >::getPtr().
template<class T , class Time > Signal<T,Time>& dynamicgraph::SignalPtr< T, Time >::operator* () [inline]
References dynamicgraph::SignalPtr< T, Time >::getPtr().
template<class T , class Time > const Signal<T,Time>* dynamicgraph::SignalPtr< T, Time >::operator-> () const [inline]
References dynamicgraph::SignalPtr< T, Time >::getPtr().
template<class T , class Time > Signal<T,Time>* dynamicgraph::SignalPtr< T, Time >::operator-> () [inline]
References dynamicgraph::SignalPtr< T, Time >::getPtr().
template<class T , class Time > virtual Signal<T,Time>& dynamicgraph::SignalPtr< T, Time >::operator= (const T & t) [inline, virtual]
Reimplemented from dynamicgraph::Signal< T, Time >.
References dynamicgraph::SignalPtr< T, Time >::setConstant().
template<class T , class Time > void dynamicgraph::SignalPtr< T, Time >::plug (SignalBase< Time > * ref) [inline, virtual]
Reimplemented from dynamicgraph::SignalBase< Time >.
References dynamicgraph::SignalPtr< T, Time >::abstractTransmitter, dynamicgraph::SignalBase< Time >::checkCompatibility(), DG_THROW, dgTDEBUG, dgTDEBUGIN, dgTDEBUGOUT, dynamicgraph::SignalBase< Time >::getName(), dynamicgraph::SignalBase< Time >::name, dynamicgraph::ExceptionSignal::PLUG_IMPOSSIBLE, dynamicgraph::SignalPtr< T, Time >::setReference(), dynamicgraph::SignalPtr< T, Time >::signalPtr, dynamicgraph::SignalPtr< T, Time >::transmitAbstract, and dynamicgraph::SignalPtr< T, Time >::transmitAbstractData.
Referenced by dynamicgraph::SignalPtr< T, Time >::setConstant(), dynamicgraph::SignalPtr< T, Time >::setFunction(), dynamicgraph::SignalPtr< T, Time >::setReference(), and dynamicgraph::SignalPtr< T, Time >::unplug().
template<class T , class Time > virtual void dynamicgraph::SignalPtr< T, Time >::removeDependency () [inline, protected, virtual]
template<class T , class Time > virtual void dynamicgraph::SignalPtr< T, Time >::setConstant (const T & t) [inline, virtual]
Reimplemented from dynamicgraph::Signal< T, Time >.
References dynamicgraph::SignalPtr< T, Time >::plug().
Referenced by dynamicgraph::SignalPtr< T, Time >::operator=(), and dynamicgraph::SignalPtr< T, Time >::setConstantDefault().
template<class T , class Time > virtual void dynamicgraph::SignalPtr< T, Time >::setConstantDefault () [inline, virtual]
Reimplemented from dynamicgraph::SignalBase< Time >.
References dynamicgraph::SignalPtr< T, Time >::accessCopy(), and dynamicgraph::SignalPtr< T, Time >::setConstantDefault().
Referenced by dynamicgraph::SignalPtr< T, Time >::setConstantDefault().
template<class T , class Time > void dynamicgraph::SignalPtr< T, Time >::setConstantDefault (const T & t) [inline]
References dynamicgraph::SignalPtr< T, Time >::modeNoThrow, and dynamicgraph::SignalPtr< T, Time >::setConstant().
template<class T , class Time > virtual void dynamicgraph::SignalPtr< T, Time >::setFunction (boost::function2< T &, T &, Time > t, typename Signal< T, Time >::Mutex * m = NULL) [inline, virtual]
References dynamicgraph::SignalPtr< T, Time >::plug().
template<class T , class Time > virtual void dynamicgraph::SignalPtr< T, Time >::setReference (const T * t, typename Signal< T, Time >::Mutex * m = NULL) [inline, virtual]
References dynamicgraph::SignalPtr< T, Time >::plug().
Referenced by dynamicgraph::SignalPtr< T, Time >::plug().
template<class T , class Time > virtual void dynamicgraph::SignalPtr< T, Time >::unplug () [inline, virtual]
Reimplemented from dynamicgraph::SignalBase< Time >.
References dynamicgraph::SignalPtr< T, Time >::plug().
template<class T , class Time > void dynamicgraph::SignalPtr< T, Time >::unsetConstantDefault () [inline]
References dynamicgraph::SignalPtr< T, Time >::modeNoThrow.
template<class T , class Time > std::ostream & dynamicgraph::SignalPtr< T, Time >::writeGraph (std::ostream & os) const [inline, virtual]
Reimplemented from dynamicgraph::SignalBase< Time >.
References dynamicgraph::SignalPtr< T, Time >::autoref(), dynamicgraph::SignalBase< Time >::ExtractNodeAndLocalNames(), dynamicgraph::SignalPtr< T, Time >::getAbstractPtr(), and dynamicgraph::SignalPtr< T, Time >::isAbstractPluged().
Member Data Documentation
template<class T , class Time > SignalBase<Time>* dynamicgraph::SignalPtr< T, Time >::abstractTransmitter [protected]
Referenced by dynamicgraph::SignalPtr< T, Time >::access(), dynamicgraph::SignalPtr< T, Time >::getAbstractPtr(), dynamicgraph::SignalPtr< T, Time >::isAbstractPluged(), and dynamicgraph::SignalPtr< T, Time >::plug().
template<class T , class Time > bool dynamicgraph::SignalPtr< T, Time >::modeNoThrow [protected]
Referenced by dynamicgraph::SignalPtr< T, Time >::access(), dynamicgraph::SignalPtr< T, Time >::accessCopy(), dynamicgraph::SignalPtr< T, Time >::setConstantDefault(), and dynamicgraph::SignalPtr< T, Time >::unsetConstantDefault().
template<class T , class Time > Signal<T,Time>* dynamicgraph::SignalPtr< T, Time >::signalPtr [protected]
Referenced by dynamicgraph::SignalPtr< T, Time >::autoref(), dynamicgraph::SignalPtr< T, Time >::display(), dynamicgraph::SignalPtr< T, Time >::getAbstractPtr(), dynamicgraph::SignalPtr< T, Time >::getPluged(), dynamicgraph::SignalPtr< T, Time >::getPtr(), dynamicgraph::SignalPtr< T, Time >::isAbstractPluged(), dynamicgraph::SignalPtr< T, Time >::isPluged(), dynamicgraph::SignalPtr< T, Time >::plug(), and dynamicgraph::SignalPtr< T, Time >::~SignalPtr().
template<class T , class Time > bool dynamicgraph::SignalPtr< T, Time >::transmitAbstract [protected]
Referenced by dynamicgraph::SignalPtr< T, Time >::access(), dynamicgraph::SignalPtr< T, Time >::accessCopy(), and dynamicgraph::SignalPtr< T, Time >::plug().
template<class T , class Time > T* dynamicgraph::SignalPtr< T, Time >::transmitAbstractData [protected]
Referenced by dynamicgraph::SignalPtr< T, Time >::access(), dynamicgraph::SignalPtr< T, Time >::accessCopy(), and dynamicgraph::SignalPtr< T, Time >::plug().