dynamicgraph::SignalCast< T > Class Template Reference
dynamicgraph::SignalCast< T > Class Template Reference
#include <dynamic-graph/signal-cast-helper.h>
Static Public Member Functions
static T cast (std::istringstream &stringValue)
static void disp (const T &t, std::ostream &os)
static void trace (const T &t, std::ostream &os)
static boost::any cast_ (std::istringstream &stringValue)
static void disp_ (const boost::any &t, std::ostream &os)
static void trace_ (const boost::any &t, std::ostream &os)
Detailed Description
template<class T>
class dynamicgraph::SignalCast< T >
This class is only used to group together static functions who differ by a template parameter. It is never actually instanced (the private constructor makes sure of that). Typical use of this class is to add the caster in the dg graph: dynamicgraph::SignalCastRegisterer sotCastRegisterer_TYPE (typeid(TYPE), SignalCast<TYPE>::disp_, SignalCast<TYPE>::cast_, SignalCast<TYPE>::trace_);
NMSD: I don't really understand the use of this additional class. IMHO (comme on dit), it should be possible to rewrite the same-spec macros using specialization of the template class DefaultCastRegisterer. No?
Member Function Documentation
template<class T > static T dynamicgraph::SignalCast< T >::cast (std::istringstream & stringValue) [inline, static]
Referenced by dynamicgraph::SignalCast< T >::cast_().
template<class T > static boost::any dynamicgraph::SignalCast< T >::cast_ (std::istringstream & stringValue) [inline, static]
References dynamicgraph::SignalCast< T >::cast().
template<class T > static void dynamicgraph::SignalCast< T >::disp (const T & t, std::ostream & os) [inline, static]
Referenced by dynamicgraph::SignalCast< T >::disp_(), and dynamicgraph::SignalCast< T >::trace().
template<class T > static void dynamicgraph::SignalCast< T >::disp_ (const boost::any & t, std::ostream & os) [inline, static]
References dynamicgraph::SignalCast< T >::disp().
template<class T > static void dynamicgraph::SignalCast< T >::trace (const T & t, std::ostream & os) [inline, static]
References dynamicgraph::SignalCast< T >::disp().
Referenced by dynamicgraph::SignalCast< T >::trace_().
template<class T > static void dynamicgraph::SignalCast< T >::trace_ (const boost::any & t, std::ostream & os) [inline, static]
References dynamicgraph::SignalCast< T >::trace().