dynamic-graph: dynamicgraph Namespace Reference
dynamicgraph Namespace Reference
This is the namespace where every object and class of this library is located.
Namespaces
namespace command
namespace dynamicgraph
Classes
class Contiifstream
class DebugTrace
class Entity
This class represents an entity, i.e. a generic computational unit that provides input and output signals.
class ExceptionAbstract
class ExceptionFactory
class ExceptionSignal
class ExceptionTraces
class FactoryStorage
The Factory class is responsible for creating Entity objects.
class EntityRegisterer
class InterpreterHelper
This class implements the first level interpretor to control basic functionnalities of the plugins.
class Interpreter
This class implements the first level interpretor to control basic functionnalities of the plugins.
class ShellFunctionRegisterer
Class for automatic registration of shell functions. Use the macro DYNAMIC-GRAPH_SHELL_FUNCTION_REGISTERER(name, fun) in a .cpp file to register functions on plugin load.
class PluginLoader
Loads plugins from dynamic libraries (usually .so or .dll files).
class PoolStorage
This class keep tracks of all the objects in the stack of Tasks.
class SignalArray_const
class SignalArray
class SignalBase
The base class for signals: not to be used as such.
class SignalCaster
class SignalCastRegisterer
class DefaultCastRegisterer
class SignalPtr
This is the only type of signal that can be plugged to, using the plug() command.
class SignalTimeDependent
A type of signal that enforces a time dependency between other signals, making sure its inputs are up to date on access, using a incrementing time tick as reference. It works this way: for a given SignalTimeDependent S, the user manually adds dependent signals through the use of the addDependency function. On access (calling the signal S operator () or access(Time) function), if the dependent signals are not up-to-date, i.e. if their [last update] time is less than the current time, their value will be access()'ed to bring them up-to-date. Thus, the value of dependent signals can be accessed quickly and repeatedly through the accessCopy() function.
class Signal
Signals link I/O ports of entities. They can be constant-valued signals, or copy the value of a heap variable, or evaluated as a function. See SignalPtr and SignalTimeDependent for other types of signals, and SignalArray for a way of grouping them.
class TimeDependency
A helper class for setting and specifying dependencies between signals.
class OutStringStream
class TracerRealTime
class Tracer
Functions
DYNAMIC_GRAPH_DLLAPI std::ostream & operator<< (std::ostream &os, const dynamicgraph::Entity &ent)
template<class Time >
SignalArray_const< Time > operator<< (const SignalBase< Time > &sig1, const SignalBase< Time > &sig2)
template<class Time >
SignalArray< Time > operator<< (SignalBase< Time > &sig1, SignalBase< Time > &sig2)
template<class Time >
std::ostream & operator<< (std::ostream &os, const SignalBase< Time > &sig)
Forward to a virtual fonction.
template<typename T >
void signal_disp (const T &value, std::ostream &os)
template<typename T >
T signal_cast (std::istringstream &iss)
template<typename T >
void signal_trace (const T &value, std::ostream &os)
void dgDEBUGF (const int, const char *,...)
void dgDEBUGF (const char *,...)
void dgERRORF (const int, const char *,...)
void dgERRORF (const char *,...)
void dgTDEBUGF (const int, const char *,...)
void dgTDEBUGF (const char *,...)
Variables
DYNAMIC_GRAPH_DLLAPI DebugTrace dgDEBUGFLOW
DYNAMIC_GRAPH_DLLAPI DebugTrace dgERRORFLOW
DYNAMIC_GRAPH_DLLAPI FactoryStorage g_factory
DYNAMIC_GRAPH_DLLAPI Interpreter g_shell
DYNAMIC_GRAPH_DLLAPI
dynamicgraph::PoolStorage g_pool
DYNAMIC_GRAPH_DLLAPI
SignalArray< int > sotNOSIGNAL
DYNAMIC_GRAPH_DLLAPI SignalCaster g_caster
The library-wide instance of SignalCaster.
Detailed Description
This is the namespace where every object and class of this library is located.
Function Documentation
void dynamicgraph::dgDEBUGF (const int, const char * , ...) [inline]
void dynamicgraph::dgDEBUGF (const char * , ...) [inline]
void dynamicgraph::dgERRORF (const int, const char * , ...) [inline]
void dynamicgraph::dgERRORF (const char * , ...) [inline]
void dynamicgraph::dgTDEBUGF (const int, const char * , ...) [inline]
References dgTDEBUG.
void dynamicgraph::dgTDEBUGF (const char * , ...) [inline]
DYNAMIC_GRAPH_DLLAPI std::ostream& dynamicgraph::operator<< (std::ostream & os, const dynamicgraph::Entity & ent)
template<class Time > std::ostream& dynamicgraph::operator<< (std::ostream & os, const SignalBase< Time > & sig)
Forward to a virtual fonction.
template<class Time > SignalArray<Time> dynamicgraph::operator<< (SignalBase< Time > & sig1, SignalBase< Time > & sig2)
template<class Time > SignalArray_const<Time> dynamicgraph::operator<< (const SignalBase< Time > & sig1, const SignalBase< Time > & sig2)
template<typename T > T dynamicgraph::signal_cast (std::istringstream & iss)
References dynamicgraph::SignalCaster::cast(), and g_caster.
Referenced by dynamicgraph::Signal< T, Time >::set().
template<typename T > void dynamicgraph::signal_disp (const T & value, std::ostream & os)
Global signal cast template (helper) functions
Using these avoid using the typeid() operator and keeps the implementation details hidden.
References dynamicgraph::SignalCaster::disp(), and g_caster.
template<typename T > void dynamicgraph::signal_trace (const T & value, std::ostream & os)
References g_caster, and dynamicgraph::SignalCaster::trace().
Variable Documentation
DYNAMIC_GRAPH_DLLAPI DebugTrace dynamicgraph::dgDEBUGFLOW
DYNAMIC_GRAPH_DLLAPI DebugTrace dynamicgraph::dgERRORFLOW
DYNAMIC_GRAPH_DLLAPI SignalCaster dynamicgraph::g_caster
The library-wide instance of SignalCaster.
Referenced by signal_cast(), signal_disp(), signal_trace(), and dynamicgraph::SignalCastRegisterer::SignalCastRegisterer().
DYNAMIC_GRAPH_DLLAPI FactoryStorage dynamicgraph::g_factory
DYNAMIC_GRAPH_DLLAPI dynamicgraph::PoolStorage dynamicgraph::g_pool
DYNAMIC_GRAPH_DLLAPI Interpreter dynamicgraph::g_shell
DYNAMIC_GRAPH_DLLAPI SignalArray<int> dynamicgraph::sotNOSIGNAL