dynamicgraph::command::Command Class Reference
dynamicgraph::command::Command Class Reference abstract
Abstract class for entity commands.
#include <dynamic-graph/command.h>
Public Member Functions
virtual ~Command ()
Command (Entity &entity, const std::vector< Value::Type > &valueTypes, const std::string &docstring)
Store the owner entity and a vector of value types.
const std::vector< Value::Type > & valueTypes () const
Return the value type of all parameters.
void setParameterValues (const std::vector< Value > &values)
Set parameter values.
const std::vector< Value > & getParameterValues () const
Get parameter values.
Value execute ()
Execute the command after checking parameters.
Entity & owner ()
Get a reference to the Entity owning this command.
std::string getDocstring () const
Get documentation string.
Static Public Attributes
static const std::vector< Value::Type > EMPTY_ARG
Protected Member Functions
virtual Value doExecute ()=0
Specific action performed by the command.
Detailed Description
Abstract class for entity commands.
This class provide a mean to control entities from external python script.
A command
is owned by an entity,
takes parameters of type Value,
return an instance of Value when calling Command::execute()
At construction, the prototype of the command is defined by providing a vector of Value::Type.
Parameters are set by calling Command::setParameterValues with a vector of Values the types of which should fit the vector specified at construction.
Constructor & Destructor Documentation
virtual dynamicgraph::command::Command::~Command () virtual
dynamicgraph::command::Command::Command (Entity & entity, const std::vector< Value::Type > & valueTypes, const std::string & docstring)
Store the owner entity and a vector of value types.
Parameters
entity reference to Entity owning this command.
valueTypes vector specifying the number and types of parameters
docstring documentation of the command
Member Function Documentation
virtual Value dynamicgraph::command::Command::doExecute () protected pure virtual
Specific action performed by the command.
Implemented in dynamicgraph::command::CommandVerbose< E >, dynamicgraph::command::CommandVoid4< E, T1, T2, T3, T4 >, dynamicgraph::command::Setter< E, Matrix >, dynamicgraph::command::CommandVoid3< E, T1, T2, T3 >, dynamicgraph::command::Setter< E, Vector >, dynamicgraph::command::Setter< E, std::string >, dynamicgraph::command::Setter< E, double >, dynamicgraph::command::CommandVoid2< E, T1, T2 >, dynamicgraph::command::Setter< E, float >, dynamicgraph::command::Setter< E, int >, dynamicgraph::command::CommandVoid1< E, T >, dynamicgraph::command::Setter< E, unsigned >, dynamicgraph::command::Getter< E, T >, dynamicgraph::command::Setter< E, T >, dynamicgraph::command::CommandVoid0< E >, dynamicgraph::command::DirectGetter< E, T >, dynamicgraph::command::DirectSetter< E, T >, and dynamicgraph::command::Setter< E, bool >.
Value dynamicgraph::command::Command::execute ()
Execute the command after checking parameters.
std::string dynamicgraph::command::Command::getDocstring () const
Get documentation string.
const std::vector<Value>& dynamicgraph::command::Command::getParameterValues () const
Get parameter values.
Referenced by dynamicgraph::command::Setter< E, bool >::doExecute(), dynamicgraph::command::DirectSetter< E, T >::doExecute(), dynamicgraph::command::CommandVoid0< E >::doExecute(), dynamicgraph::command::Setter< E, unsigned >::doExecute(), dynamicgraph::command::CommandVoid1< E, T >::doExecute(), dynamicgraph::command::Setter< E, int >::doExecute(), dynamicgraph::command::Setter< E, float >::doExecute(), dynamicgraph::command::CommandVoid2< E, T1, T2 >::doExecute(), dynamicgraph::command::Setter< E, double >::doExecute(), dynamicgraph::command::Setter< E, std::string >::doExecute(), dynamicgraph::command::Setter< E, Vector >::doExecute(), dynamicgraph::command::CommandVoid3< E, T1, T2, T3 >::doExecute(), dynamicgraph::command::Setter< E, Matrix >::doExecute(), dynamicgraph::command::CommandVoid4< E, T1, T2, T3, T4 >::doExecute(), and dynamicgraph::command::CommandVerbose< E >::doExecute().
Entity& dynamicgraph::command::Command::owner ()
Get a reference to the Entity owning this command.
Referenced by dynamicgraph::command::Setter< E, bool >::doExecute(), dynamicgraph::command::Getter< E, T >::doExecute(), dynamicgraph::command::Setter< E, unsigned >::doExecute(), dynamicgraph::command::Setter< E, int >::doExecute(), dynamicgraph::command::Setter< E, float >::doExecute(), dynamicgraph::command::Setter< E, double >::doExecute(), dynamicgraph::command::Setter< E, std::string >::doExecute(), dynamicgraph::command::Setter< E, Vector >::doExecute(), and dynamicgraph::command::Setter< E, Matrix >::doExecute().
void dynamicgraph::command::Command::setParameterValues (const std::vector< Value > & values)
Set parameter values.
const std::vector<Value::Type>& dynamicgraph::command::Command::valueTypes () const
Return the value type of all parameters.
Member Data Documentation
const std::vector<Value::Type> dynamicgraph::command::Command::EMPTY_ARG static