dynamicgraph::SignalArray_const< Time > Class Template Reference
dynamicgraph::SignalArray_const< Time > Class Template Reference
Core classes and objects
TODO.
#include <dynamic-graph/signal-array.h>
Public Member Functions
SignalArray_const (const unsigned int &sizeARG=DEFAULT_SIZE)
SignalArray_const (const SignalBase< Time > &sig)
SignalArray_const (const SignalArray< Time > &siga)
SignalArray_const (const SignalArray_const< Time > &siga)
virtual ~SignalArray_const ()
virtual SignalArray_const< Time > & operator<< (const SignalBase< Time > &sig)
virtual const SignalBase< Time > & operator[] (const unsigned int &idx) const
virtual unsigned int getSize () const
Static Public Attributes
static const int DEFAULT_SIZE = 20
Protected Member Functions
void createArray ()
void addElmt (const SignalBase< Time > *el)
Protected Attributes
const SignalBase< Time > ** const_array
unsigned int size
unsigned int rank
Detailed Description
template<class Time>
class dynamicgraph::SignalArray_const< Time >
TODO.
Constructor & Destructor Documentation
template<class Time> dynamicgraph::SignalArray_const< Time >::SignalArray_const (const unsigned int & sizeARG = DEFAULT_SIZE) [inline]
References dynamicgraph::SignalArray_const< Time >::createArray().
template<class Time> dynamicgraph::SignalArray_const< Time >::SignalArray_const (const SignalBase< Time > & sig) [inline]
References dynamicgraph::SignalArray_const< Time >::addElmt(), and dynamicgraph::SignalArray_const< Time >::createArray().
template<class Time> dynamicgraph::SignalArray_const< Time >::SignalArray_const (const SignalArray< Time > & siga) [inline]
References dynamicgraph::SignalArray_const< Time >::const_array, dynamicgraph::SignalArray_const< Time >::createArray(), and dynamicgraph::SignalArray_const< Time >::rank.
template<class Time> dynamicgraph::SignalArray_const< Time >::SignalArray_const (const SignalArray_const< Time > & siga) [inline]
References dynamicgraph::SignalArray_const< Time >::const_array, dynamicgraph::SignalArray_const< Time >::createArray(), and dynamicgraph::SignalArray_const< Time >::rank.
template<class Time> virtual dynamicgraph::SignalArray_const< Time >::~SignalArray_const () [inline, virtual]
References dynamicgraph::SignalArray_const< Time >::const_array.
Member Function Documentation
template<class Time> void dynamicgraph::SignalArray_const< Time >::addElmt (const SignalBase< Time > * el) [inline, protected]
References dynamicgraph::SignalArray_const< Time >::const_array, dynamicgraph::SignalArray_const< Time >::rank, and dynamicgraph::SignalArray_const< Time >::size.
Referenced by dynamicgraph::SignalArray_const< Time >::operator<<(), and dynamicgraph::SignalArray_const< Time >::SignalArray_const().
template<class Time> void dynamicgraph::SignalArray_const< Time >::createArray () [inline, protected]
Reimplemented in dynamicgraph::SignalArray< Time >.
References dynamicgraph::SignalArray_const< Time >::const_array, and dynamicgraph::SignalArray_const< Time >::size.
Referenced by dynamicgraph::SignalArray_const< Time >::SignalArray_const().
template<class Time> virtual unsigned int dynamicgraph::SignalArray_const< Time >::getSize () const [inline, virtual]
References dynamicgraph::SignalArray_const< Time >::rank.
Referenced by dynamicgraph::TimeDependency< Time >::TimeDependency().
template<class Time> virtual SignalArray_const<Time>& dynamicgraph::SignalArray_const< Time >::operator<< (const SignalBase< Time > & sig) [inline, virtual]
References dynamicgraph::SignalArray_const< Time >::addElmt().
template<class Time> virtual const SignalBase<Time>& dynamicgraph::SignalArray_const< Time >::operator[] (const unsigned int & idx) const [inline, virtual]
Reimplemented in dynamicgraph::SignalArray< Time >.
References dynamicgraph::SignalArray_const< Time >::const_array.
Member Data Documentation
template<class Time> const SignalBase<Time>** dynamicgraph::SignalArray_const< Time >::const_array [protected]
Referenced by dynamicgraph::SignalArray_const< Time >::addElmt(), dynamicgraph::SignalArray_const< Time >::createArray(), dynamicgraph::SignalArray_const< Time >::operator[](), dynamicgraph::SignalArray_const< Time >::SignalArray_const(), and dynamicgraph::SignalArray_const< Time >::~SignalArray_const().
template<class Time> const int dynamicgraph::SignalArray_const< Time >::DEFAULT_SIZE = 20 [static]
template<class Time> unsigned int dynamicgraph::SignalArray_const< Time >::rank [protected]
Referenced by dynamicgraph::SignalArray_const< Time >::addElmt(), dynamicgraph::SignalArray< Time >::addElmt(), dynamicgraph::SignalArray_const< Time >::getSize(), dynamicgraph::SignalArray< Time >::SignalArray(), and dynamicgraph::SignalArray_const< Time >::SignalArray_const().
template<class Time> unsigned int dynamicgraph::SignalArray_const< Time >::size [protected]
Referenced by dynamicgraph::SignalArray_const< Time >::addElmt(), dynamicgraph::SignalArray< Time >::addElmt(), dynamicgraph::SignalArray_const< Time >::createArray(), dynamicgraph::SignalArray< Time >::createArray(), dynamicgraph::SignalArray< Time >::operator<<(), and dynamicgraph::SignalArray< Time >::SignalArray().