dynamicgraph Namespace Reference
dynamicgraph Namespace Reference
WIN32.
Namespaces
command
Classes
class Contiifstream
TODO.
class DebugTrace
Logging class.
class DefaultCastRegisterer
This class can be used to register default casts, i.e.
class Entity
This class represents an entity, i.e.
struct EntityHelper
class EntityRegisterer
This class automatically register an Entity to the global factory at initialization and unregister it during instance destruction.
class ExceptionAbstract
Abstract root class for all dynamic-graph exceptions.
class ExceptionFactory
Generic error class.
class ExceptionSignal
Exceptions raised when an error related to signals happen.
class ExceptionTraces
Exceptions raised when an error related to traces happen.
class FactoryStorage
Provides a way to create Entity objects from their class name.
class OutStringStream
Stream for the tracer real-time.
class PoolStorage
Singleton that keeps track of all the entities.
class Signal
Signals link I/O ports of entities. They can be constant-valued signals, or copy the value of a heap variable, or evaluated as a function. See SignalPtr and SignalTimeDependent for other types of signals, and SignalArray for a way of grouping them.
class SignalArray
TODO.
class SignalArray_const
TODO.
class SignalBase
The base class for signals: not to be used as such.
class SignalCast
class SignalCaster
This singleton class allows serialization of a number of objects into (disp) and from (cast) std i/o streams.
class SignalCastRegisterer
The SignalCast registerer class.
class SignalPtr
This is the only type of signal that can be plugged to, using the plug () command.
class SignalTimeDependent
A type of signal that enforces a time dependency between other signals, making sure its inputs are up to date on access, using a incrementing time tick as reference. It works this way: for a given SignalTimeDependent S, the user manually adds dependent signals through the use of the addDependency function. On access (calling the signal S operator () or access(Time) function), if the dependent signals are not up-to-date, i.e. if their [last update] time is less than the current time, their value will be access ()'ed to bring them up-to-date. Thus, the value of dependent signals can be accessed quickly and repeatedly through the accessCopy () function.
class TimeDependency
A helper class for setting and specifying dependencies between signals.
class Tracer
Tracer plug-in main class.
class TracerRealTime
Main class of the tracer real-time plug-in.
Typedefs
typedef Eigen::MatrixXd Matrix
typedef Eigen::VectorXd Vector
Functions
DYNAMIC_GRAPH_DLLAPI std::ostream & operator<< (std::ostream &os, const dynamicgraph::Entity &ent)
PoolStorage & g_pool ()
template<class Time >
SignalArray_const< Time > operator<< (const SignalBase< Time > &sig1, const SignalBase< Time > &sig2)
template<class Time >
SignalArray< Time > operator<< (SignalBase< Time > &sig1, SignalBase< Time > &sig2)
template<class Time >
std::ostream & operator<< (std::ostream &os, const SignalBase< Time > &sig)
Forward to a virtual fonction.
template<typename T >
void signal_disp (const T &value, std::ostream &os)
Global signal cast template (helper) functions.
template<typename T >
T signal_cast (std::istringstream &iss)
template<typename T >
void signal_trace (const T &value, std::ostream &os)
Variables
DYNAMIC_GRAPH_DLLAPI DebugTrace dgDEBUGFLOW
DYNAMIC_GRAPH_DLLAPI DebugTrace dgERRORFLOW
class {
} nullptr = {}
DYNAMIC_GRAPH_DLLAPI SignalArray< int > sotNOSIGNAL
Detailed Description
WIN32.
This is the namespace where every object and class of this library is located.
Typedef Documentation
typedef Eigen::MatrixXd dynamicgraph::Matrix
typedef Eigen::VectorXd dynamicgraph::Vector
Function Documentation
PoolStorage& dynamicgraph::g_pool () inline
References dynamicgraph::PoolStorage::getInstance().
DYNAMIC_GRAPH_DLLAPI std::ostream& dynamicgraph::operator<< (std::ostream & os, const dynamicgraph::Entity & ent)
Referenced by dynamicgraph::ExceptionAbstract::what().
template<class Time > SignalArray<Time> dynamicgraph::operator<< (SignalBase< Time > & sig1, SignalBase< Time > & sig2)
References sotNOSIGNAL.
template<class Time > SignalArray_const<Time> dynamicgraph::operator<< (const SignalBase< Time > & sig1, const SignalBase< Time > & sig2)
template<class Time > std::ostream& dynamicgraph::operator<< (std::ostream & os, const SignalBase< Time > & sig)
Forward to a virtual fonction.
template<typename T > T dynamicgraph::signal_cast (std::istringstream & iss)
References dynamicgraph::SignalCaster::cast(), and dynamicgraph::SignalCaster::getInstance().
Referenced by dynamicgraph::Signal< T, Time >::set().
template<typename T > void dynamicgraph::signal_disp (const T & value, std::ostream & os)
Global signal cast template (helper) functions.
Using these avoid using the typeid () operator and keeps the implementation details hidden.
References dynamicgraph::SignalCaster::disp(), and dynamicgraph::SignalCaster::getInstance().
template<typename T > void dynamicgraph::signal_trace (const T & value, std::ostream & os)
References dynamicgraph::SignalCaster::getInstance(), and dynamicgraph::SignalCaster::trace().
Variable Documentation
DYNAMIC_GRAPH_DLLAPI DebugTrace dynamicgraph::dgDEBUGFLOW
DYNAMIC_GRAPH_DLLAPI DebugTrace dynamicgraph::dgERRORFLOW
const { ... } dynamicgraph::nullptr
DYNAMIC_GRAPH_DLLAPI SignalArray<int> dynamicgraph::sotNOSIGNAL
Referenced by operator<<().