dynamic-graph: dynamicgraph::SignalTimeDependent< T, Time > Class Template Reference
dynamicgraph::SignalTimeDependent< T, Time > Class Template Reference
A type of signal that enforces a time dependency between other signals, making sure its inputs are up to date on access, using a incrementing time tick as reference. It works this way: for a given SignalTimeDependent S, the user manually adds dependent signals through the use of the addDependency function. On access (calling the signal S operator () or access(Time) function), if the dependent signals are not up-to-date, i.e. if their [last update] time is less than the current time, their value will be access()'ed to bring them up-to-date. Thus, the value of dependent signals can be accessed quickly and repeatedly through the accessCopy() function.
#include <dynamic-graph/signal-time-dependent.h>
Public Member Functions
SignalTimeDependent (std::string name="")
SignalTimeDependent (const SignalArray_const< Time > &arr, std::string name="")
SignalTimeDependent (boost::function2< T &, T &, Time > t, const SignalArray_const< Time > &sig, std::string name="")
virtual ~SignalTimeDependent (void)
const T & operator() (const Time &t1)
const T & access (const Time &t1)
virtual void addDependency (const SignalBase< Time > &signal)
virtual void removeDependency (const SignalBase< Time > &signal)
virtual void clearDependencies (void)
std::ostream & writeGraph (std::ostream &os) const
std::ostream & displayDependencies (std::ostream &os, const int depth=-1, std::string space="", std::string next1="", std::string next2="") const
virtual bool needUpdate (const Time &t) const
virtual void setPeriodTime (const Time &p)
virtual Time getPeriodTime (void) const
Detailed Description
template<class T, class Time>
class dynamicgraph::SignalTimeDependent< T, Time >
A type of signal that enforces a time dependency between other signals, making sure its inputs are up to date on access, using a incrementing time tick as reference. It works this way: for a given SignalTimeDependent S, the user manually adds dependent signals through the use of the addDependency function. On access (calling the signal S operator () or access(Time) function), if the dependent signals are not up-to-date, i.e. if their [last update] time is less than the current time, their value will be access()'ed to bring them up-to-date. Thus, the value of dependent signals can be accessed quickly and repeatedly through the accessCopy() function.
Constructor & Destructor Documentation
template<class T , class Time > dynamicgraph::SignalTimeDependent< T, Time >::SignalTimeDependent (std::string name = "")
template<class T , class Time> dynamicgraph::SignalTimeDependent< T, Time >::SignalTimeDependent (const SignalArray_const< Time > & arr, std::string name = "")
template<class T, class Time> dynamicgraph::SignalTimeDependent< T, Time >::SignalTimeDependent (boost::function2< T &, T &, Time > t, const SignalArray_const< Time > & sig, std::string name = "")
References dynamicgraph::Signal< T, Time >::setFunction().
template<class T, class Time> virtual dynamicgraph::SignalTimeDependent< T, Time >::~SignalTimeDependent (void) [inline, virtual]
Member Function Documentation
template<class T , class Time> const T & dynamicgraph::SignalTimeDependent< T, Time >::access (const Time & t1) [virtual]
Reimplemented from dynamicgraph::Signal< T, Time >.
References dynamicgraph::Signal< T, Time >::access(), dynamicgraph::Signal< T, Time >::accessCopy(), dynamicgraph::TimeDependency< Time >::needUpdate(), and dynamicgraph::SignalBase< Time >::setReady().
Referenced by dynamicgraph::SignalTimeDependent< int, int >::operator()().
template<class T , class Time> void dynamicgraph::SignalTimeDependent< T, Time >::addDependency (const SignalBase< Time > & signal) [virtual]
Reimplemented from dynamicgraph::TimeDependency< Time >.
References dynamicgraph::TimeDependency< Time >::addDependency().
template<class T , class Time > void dynamicgraph::SignalTimeDependent< T, Time >::clearDependencies (void) [virtual]
Reimplemented from dynamicgraph::SignalBase< Time >.
References dynamicgraph::TimeDependency< Time >::clearDependency().
template<class T, class Time> std::ostream& dynamicgraph::SignalTimeDependent< T, Time >::displayDependencies (std::ostream & os, const int depth = -1, std::string space = "", std::string next1 = "", std::string next2 = "") const [inline]
Reimplemented from dynamicgraph::TimeDependency< Time >.
Referenced by dynamicgraph::SignalTimeDependent< int, int >::displayDependencies().
template<class T , class Time > Time dynamicgraph::SignalTimeDependent< T, Time >::getPeriodTime (void) const [virtual]
Reimplemented from dynamicgraph::TimeDependency< Time >.
References dynamicgraph::TimeDependency< Time >::getPeriodTime().
template<class T , class Time> bool dynamicgraph::SignalTimeDependent< T, Time >::needUpdate (const Time & t) const [virtual]
Reimplemented from dynamicgraph::TimeDependency< Time >.
References dynamicgraph::TimeDependency< Time >::needUpdate().
template<class T, class Time> const T& dynamicgraph::SignalTimeDependent< T, Time >::operator() (const Time & t1) [inline, virtual]
Reimplemented from dynamicgraph::Signal< T, Time >.
template<class T , class Time> void dynamicgraph::SignalTimeDependent< T, Time >::removeDependency (const SignalBase< Time > & signal) [virtual]
Reimplemented from dynamicgraph::TimeDependency< Time >.
References dynamicgraph::TimeDependency< Time >::removeDependency().
template<class T , class Time> void dynamicgraph::SignalTimeDependent< T, Time >::setPeriodTime (const Time & p) [virtual]
Reimplemented from dynamicgraph::TimeDependency< Time >.
References dynamicgraph::TimeDependency< Time >::setPeriodTime().
template<class T, class Time> std::ostream& dynamicgraph::SignalTimeDependent< T, Time >::writeGraph (std::ostream & os) const [inline, virtual]
Reimplemented from dynamicgraph::TimeDependency< Time >.