dynamic-graph: dynamicgraph::SignalPtr< T, Time > Class Template Reference
dynamicgraph::SignalPtr< T, Time > Class Template Reference
This is the only type of signal that can be plugged to, using the plug() command.
#include <dynamic-graph/signal-ptr.h>
Public Member Functions
SignalPtr (Signal< T, Time > *ptr, std::string name="")
virtual ~SignalPtr (void)
Signal< T, Time > * getPtr (void)
const Signal< T, Time > * getPtr (void) const
SignalBase< Time > * getAbstractPtr (void)
const SignalBase< Time > * getAbstractPtr (void) const
virtual void plug (SignalBase< Time > *ref)
virtual void unplug (void)
virtual bool isPluged (void) const
virtual SignalBase< Time > * getPluged (void) const
virtual bool isAbstractPluged (void) const
virtual const Time & getTime (void) const
Signal< T, Time > * operator-> ()
const Signal< T, Time > * operator-> () const
Signal< T, Time > & operator* (void)
const Signal< T, Time > & operator* (void) const
operator bool (void) const
virtual bool needUpdate (const Time &t) const
virtual std::ostream & writeGraph (std::ostream &os) const
virtual std::ostream & display (std::ostream &os) const
virtual const T & operator() (const Time &t)
virtual const T & access (const Time &t)
virtual const T & accessCopy (void) const
void setConstantDefault (const T &t)
virtual void setConstantDefault (void)
void unsetConstantDefault (void)
virtual void setConstant (const T &t)
virtual void setReference (const T *t, typename Signal< T, Time >::Mutex *m=NULL)
virtual void setFunction (boost::function2< T &, T &, Time > t, typename Signal< T, Time >::Mutex *m=NULL)
virtual Signal< T, Time > & operator= (const T &t)
virtual std::ostream & displayDependencies (std::ostream &os, const int depth=-1, std::string space="", std::string next1="", std::string next2="") const
Protected Member Functions
bool autoref (void) const
virtual void addDependency ()
virtual void removeDependency ()
virtual void clearDependencies ()
Protected Attributes
Signal< T, Time > * signalPtr
bool modeNoThrow
bool transmitAbstract
SignalBase< Time > * abstractTransmitter
T * transmitAbstractData
Detailed Description
template<class T, class Time>
class dynamicgraph::SignalPtr< T, Time >
This is the only type of signal that can be plugged to, using the plug() command.
In that sense, when plugged into, it acts as a "pointer" to the input signal, hence the name. Operator -> is also overloaded and can be used to access the pointed signal.
Constructor & Destructor Documentation
template<class T , class Time > dynamicgraph::SignalPtr< T, Time >::SignalPtr (Signal< T, Time > * ptr, std::string name = "") [inline]
template<class T , class Time > virtual dynamicgraph::SignalPtr< T, Time >::~SignalPtr (void) [inline, virtual]
References dynamicgraph::SignalPtr< T, Time >::signalPtr.
Member Function Documentation
template<class T , class Time > const T & dynamicgraph::SignalPtr< T, Time >::access (const Time & t) [virtual]
Reimplemented from dynamicgraph::Signal< T, Time >.
References dynamicgraph::Signal< T, Time >::access(), dynamicgraph::Signal< T, Time >::accessCopy(), dgTDEBUGIN, and dgTDEBUGOUT.
template<class T , class Time > const T & dynamicgraph::SignalPtr< T, Time >::accessCopy (void) const [virtual]
Reimplemented from dynamicgraph::Signal< T, Time >.
References dynamicgraph::Signal< T, Time >::accessCopy().
Referenced by dynamicgraph::SignalPtr< T, Time >::setConstantDefault().
template<class T , class Time > virtual void dynamicgraph::SignalPtr< T, Time >::addDependency () [inline, protected, virtual]
template<class T , class Time > bool dynamicgraph::SignalPtr< T, Time >::autoref (void) const [inline, protected]
References dynamicgraph::SignalPtr< T, Time >::signalPtr.
template<class T , class Time > virtual void dynamicgraph::SignalPtr< T, Time >::clearDependencies (void) [inline, protected, virtual]
Reimplemented from dynamicgraph::SignalBase< Time >.
template<class T , class Time > std::ostream & dynamicgraph::SignalPtr< T, Time >::display (std::ostream & os) const [virtual]
Reimplemented from dynamicgraph::Signal< T, Time >.
References dgTDEBUGIN, dgTDEBUGOUT, and dynamicgraph::Signal< T, Time >::display().
template<class T , class Time > std::ostream & dynamicgraph::SignalPtr< T, Time >::displayDependencies (std::ostream & os, const int depth = -1, std::string space = "", std::string next1 = "", std::string next2 = "") const [virtual]
Reimplemented from dynamicgraph::SignalBase< Time >.
References dgTDEBUGIN, dgTDEBUGOUT, and dynamicgraph::SignalBase< Time >::displayDependencies().
template<class T , class Time > SignalBase< Time > * dynamicgraph::SignalPtr< T, Time >::getAbstractPtr (void)
References DG_THROW, and dynamicgraph::ExceptionSignal::NOT_INITIALIZED.
template<class T , class Time > const SignalBase< Time > * dynamicgraph::SignalPtr< T, Time >::getAbstractPtr (void) const
References DG_THROW, and dynamicgraph::ExceptionSignal::NOT_INITIALIZED.
template<class T , class Time > virtual SignalBase<Time>* dynamicgraph::SignalPtr< T, Time >::getPluged (void) const [inline, virtual]
Reimplemented from dynamicgraph::SignalBase< Time >.
References dynamicgraph::SignalPtr< T, Time >::signalPtr.
template<class T , class Time > Signal< T, Time > * dynamicgraph::SignalPtr< T, Time >::getPtr (void)
References DG_THROW, dgTDEBUGIN, dgTDEBUGOUT, and dynamicgraph::ExceptionSignal::NOT_INITIALIZED.
Referenced by dynamicgraph::SignalPtr< T, Time >::operator*(), and dynamicgraph::SignalPtr< T, Time >::operator->().
template<class T , class Time > const Signal< T, Time > * dynamicgraph::SignalPtr< T, Time >::getPtr (void) const
References DG_THROW, dgTDEBUGIN, dgTDEBUGOUT, and dynamicgraph::ExceptionSignal::NOT_INITIALIZED.
template<class T , class Time > const Time & dynamicgraph::SignalPtr< T, Time >::getTime (void) const [virtual]
Reimplemented from dynamicgraph::SignalBase< Time >.
References dynamicgraph::SignalBase< Time >::getTime().
template<class T , class Time > bool dynamicgraph::SignalPtr< T, Time >::isAbstractPluged (void) const [virtual]
template<class T , class Time > virtual bool dynamicgraph::SignalPtr< T, Time >::isPluged (void) const [inline, virtual]
Reimplemented from dynamicgraph::SignalBase< Time >.
References dynamicgraph::SignalPtr< T, Time >::signalPtr.
Referenced by dynamicgraph::SignalPtr< T, Time >::operator bool().
template<class T , class Time > bool dynamicgraph::SignalPtr< T, Time >::needUpdate (const Time & t) const [virtual]
Reimplemented from dynamicgraph::SignalBase< Time >.
References dynamicgraph::SignalBase< Time >::needUpdate().
template<class T , class Time > dynamicgraph::SignalPtr< T, Time >::operator bool (void) const [inline]
References dynamicgraph::SignalPtr< T, Time >::isPluged().
template<class T , class Time > const T & dynamicgraph::SignalPtr< T, Time >::operator() (const Time & t) [virtual]
Reimplemented from dynamicgraph::Signal< T, Time >.
template<class T , class Time > Signal<T,Time>& dynamicgraph::SignalPtr< T, Time >::operator* (void) [inline]
References dynamicgraph::SignalPtr< T, Time >::getPtr().
template<class T , class Time > const Signal<T,Time>& dynamicgraph::SignalPtr< T, Time >::operator* (void) const [inline]
References dynamicgraph::SignalPtr< T, Time >::getPtr().
template<class T , class Time > Signal<T,Time>* dynamicgraph::SignalPtr< T, Time >::operator-> () [inline]
References dynamicgraph::SignalPtr< T, Time >::getPtr().
template<class T , class Time > const Signal<T,Time>* dynamicgraph::SignalPtr< T, Time >::operator-> () const [inline]
References dynamicgraph::SignalPtr< T, Time >::getPtr().
template<class T , class Time > virtual Signal<T,Time>& dynamicgraph::SignalPtr< T, Time >::operator= (const T & t) [inline, virtual]
Reimplemented from dynamicgraph::Signal< T, Time >.
References dynamicgraph::SignalPtr< T, Time >::setConstant().
template<class T , class Time > void dynamicgraph::SignalPtr< T, Time >::plug (SignalBase< Time > * ref) [virtual]
Reimplemented from dynamicgraph::SignalBase< Time >.
References dynamicgraph::SignalBase< Time >::checkCompatibility(), DG_THROW, dgTDEBUG, dgTDEBUGIN, dgTDEBUGOUT, dynamicgraph::SignalBase< Time >::getName(), dynamicgraph::ExceptionSignal::PLUG_IMPOSSIBLE, and dynamicgraph::Signal< T, Time >::setReference().
Referenced by dynamicgraph::SignalPtr< T, Time >::setConstant(), dynamicgraph::SignalPtr< T, Time >::setFunction(), dynamicgraph::SignalPtr< T, Time >::setReference(), and dynamicgraph::SignalPtr< T, Time >::unplug().
template<class T , class Time > virtual void dynamicgraph::SignalPtr< T, Time >::removeDependency () [inline, protected, virtual]
template<class T , class Time > virtual void dynamicgraph::SignalPtr< T, Time >::setConstant (const T & t) [inline, virtual]
Reimplemented from dynamicgraph::Signal< T, Time >.
References dynamicgraph::SignalPtr< T, Time >::plug().
Referenced by dynamicgraph::SignalPtr< T, Time >::operator=(), and dynamicgraph::SignalPtr< T, Time >::setConstantDefault().
template<class T , class Time > virtual void dynamicgraph::SignalPtr< T, Time >::setConstantDefault (void) [inline, virtual]
Reimplemented from dynamicgraph::SignalBase< Time >.
References dynamicgraph::SignalPtr< T, Time >::accessCopy(), and dynamicgraph::SignalPtr< T, Time >::setConstantDefault().
Referenced by dynamicgraph::SignalPtr< T, Time >::setConstantDefault().
template<class T , class Time > void dynamicgraph::SignalPtr< T, Time >::setConstantDefault (const T & t) [inline]
References dynamicgraph::SignalPtr< T, Time >::modeNoThrow, and dynamicgraph::SignalPtr< T, Time >::setConstant().
template<class T , class Time > virtual void dynamicgraph::SignalPtr< T, Time >::setFunction (boost::function2< T &, T &, Time > t, typename Signal< T, Time >::Mutex * m = NULL) [inline, virtual]
References dynamicgraph::SignalPtr< T, Time >::plug().
template<class T , class Time > virtual void dynamicgraph::SignalPtr< T, Time >::setReference (const T * t, typename Signal< T, Time >::Mutex * m = NULL) [inline, virtual]
References dynamicgraph::SignalPtr< T, Time >::plug().
template<class T , class Time > virtual void dynamicgraph::SignalPtr< T, Time >::unplug (void) [inline, virtual]
Reimplemented from dynamicgraph::SignalBase< Time >.
References dynamicgraph::SignalPtr< T, Time >::plug().
template<class T , class Time > void dynamicgraph::SignalPtr< T, Time >::unsetConstantDefault (void) [inline]
References dynamicgraph::SignalPtr< T, Time >::modeNoThrow.
template<class T , class Time > std::ostream & dynamicgraph::SignalPtr< T, Time >::writeGraph (std::ostream & os) const [virtual]
Reimplemented from dynamicgraph::SignalBase< Time >.
References dynamicgraph::SignalBase< Time >::ExtractNodeAndLocalNames().
Member Data Documentation
template<class T , class Time > SignalBase<Time>* dynamicgraph::SignalPtr< T, Time >::abstractTransmitter [protected]
template<class T , class Time > bool dynamicgraph::SignalPtr< T, Time >::modeNoThrow [protected]
Referenced by dynamicgraph::SignalPtr< T, Time >::setConstantDefault(), and dynamicgraph::SignalPtr< T, Time >::unsetConstantDefault().
template<class T , class Time > Signal<T,Time>* dynamicgraph::SignalPtr< T, Time >::signalPtr [protected]
Referenced by dynamicgraph::SignalPtr< T, Time >::autoref(), dynamicgraph::SignalPtr< T, Time >::getPluged(), dynamicgraph::SignalPtr< T, Time >::isPluged(), and dynamicgraph::SignalPtr< T, Time >::~SignalPtr().
template<class T , class Time > bool dynamicgraph::SignalPtr< T, Time >::transmitAbstract [protected]
template<class T , class Time > T* dynamicgraph::SignalPtr< T, Time >::transmitAbstractData [protected]