#!/bin/sh
set -ev

# Directories.
root_dir=`pwd`
build_dir="$root_dir/_travis/build"
install_dir="$root_dir/_travis/install"
jrl_mathtools_dir="$build_dir/jrl-mathtools"
jrl_mal_dir="$build_dir/jrl-mal"

# Shortcuts.
git_clone="git clone --quiet --recursive"

# Create layout.
rm -rf "$build_dir" "$install_dir"
mkdir -p "$build_dir"
mkdir -p "$install_dir"

# Setup environment variables.
export LD_LIBRARY_PATH="$install_dir/lib:$LD_LIBRARY_PATH"
export PKG_CONFIG_PATH="$install_dir/lib/pkgconfig:$PKG_CONFIG_PATH"

# Retrieve jrl-mathtools
echo "--> Compiling jrl-mathtools"
cd "$build_dir"
$git_clone "git://github.com/jrl-umi3218/jrl-mathtools.git"
cd "$jrl_mathtools_dir"
cmake . -DCMAKE_INSTALL_PREFIX:STRING="$install_dir"
make install

# Retrieve jrl-mal
echo "--> Compiling jrl-mal"
cd "$build_dir"
$git_clone "git://github.com/jrl-umi3218/jrl-mal.git"
cd "$jrl_mal_dir"
cmake . -DCMAKE_INSTALL_PREFIX:STRING="$install_dir"
make install

# Compile metapod and run tests
cd "$build_dir"
cmake "$root_dir" -DCMAKE_INSTALL_PREFIX="$install_dir"		\
		  -DCMAKE_CXX_FLAGS="--coverage"		\
		  -DCMAKE_EXE_LINKER_FLAGS="--coverage"		\
		  -DCMAKE_MODULE_LINKER_FLAGS="--coverage"	\
		  -DCMAKE_INSTALL_PREFIX:STRING="$install_dir"
make
make test
make install
